# Generated by Django 3.2.8 on 2021-10-20 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('phone', models.IntegerField()),
                ('files', models.FileField(null=True, upload_to='')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
