# Generated by Django 3.2.8 on 2021-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0002_alter_info_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='files',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
